# Application Running Port
server:
  port: 8082
  
# Application name    
spring:
  application:
    name: USER-API
# Register Application With Admin Server
  boot:
    admin:
      client:
        url: http://localhost:1111/
# Register Application With Eureka Server
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

# Enable All Actuator End Points
management:
  endpoints:
    web:
      exposure:
        include: '*'