# Application Running Port
server:
  port: 8083
  
# Application name    
spring:
  application:
    name: AR-API
# Register Application With Admin Server
#  boot:
#    admin:
#      client:
#        url: http://localhost:1111/
        
# Data base Connection
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/rihs_db
    username: root
    password: root
    #JPA Configurations
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
# Register Application With Eureka Server
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

# Enable All Actuator End Points
management:
  endpoints:
    web:
      exposure:
        include: '*'
        